C:\Users\feder\OneDrive\Escritorio\Viajando 2026\Viajando2025\Viajando  (2)\Viajando> git pull PS C:\Users\feder\OneDrive\Escritorio\Viajando 2026\Viajando2025\Viajando (2)\Viajando> git pull PS C:\Users\feder\OneDrive\Escritorio\Viajando 2026\Viajando2025\Viajando (2)\Viajando> git pull PS C:\Users\feder\OneDrive\Escritorio\Viajando 2026\Viajando2025\Viajando (2)\Viajando> git pull
 Auto-merging Viajando (2)/Viajando/interfazPpal/Frms
 Paquetes/FrmIngresarEditarPaquetes.Designer.cs

 CONFLICT (content): Merge conflict in Viajando
 (2)/Viajando/interfazPpal/Frms
 Paquetes/FrmIngresarEditarPaquetes.Designer.cs

 Auto-merging Viajando (2)/Viajando/interfazPpal/Frms
 Paquetes/FrmIngresarEditarPaquetes.cs

 CONFLICT (content): Merge conflict in Viajando
 (2)/Viajando/interfazPpal/Frms Paquetes/FrmIngresarEditarPaquetes.cs

 error: could not apply ef00c54... .

 hint: Resolve all conflicts manually, mark them as resolved with

 hint: "git add/rm <conflicted_files>", then run "git rebase
 --continue".

 hint: You can instead skip this commit: run "git rebase --skip".

 hint: To abort and get back to the state before "git rebase", run "git
 rebase --abort".

 hint: Disable this message with "git config advice.mergeConflict false"

 Could not apply ef00c54... .git rebase --skip

Auto-merging Viajando (2)/Viajando/interfazPpal/Frms Paquetes/FrmIngresarEditarPaquetes.Designer.cs
CONFLICT (content): Merge conflict in Viajando (2)/Viajando/interfazPpal/Frms Paquetes/FrmIngresarEditarPaquetes.Designer.cs
Auto-merging Viajando (2)/Viajando/interfazPpal/Frms Paquetes/FrmIngresarEditarPaquetes.cs
CONFLICT (content): Merge conflict in Viajando (2)/Viajando/interfazPpal/Frms Paquetes/FrmIngresarEditarPaquetes.cs
error: could not apply ef00c54... .
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config advice.mergeConflict false"
Could not apply ef00c54... ..

git status